name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch: # allows manual triggering of the workflow

  push:
    branches:
      - master  # triggers when a push is made to the master branch

jobs:
  generate:
    permissions:
      contents: write  # allows the action to write to the repository contents
    runs-on: ubuntu-latest  # runs on the latest Ubuntu environment

    timeout-minutes: 5  # set a timeout of 5 minutes for this job

    steps:
      # Step 1: Generate snake.svg for light mode
      - name: generate snake-light.svg for light mode
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: amirayed7  # Your GitHub username
          outputs: dist/snake-light.svg?palette=github  # Light palette

      # Step 2: Generate snake.svg for dark mode
      - name: generate snake-dark.svg for dark mode
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: amirayed7  # Your GitHub username
          outputs: dist/snake-dark.svg?palette=github-dark  # Dark palette

      # Step 3: Push the generated SVGs to the output branch
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Action to push to the output branch
        with:
          target_branch: output  # Target branch for the SVG files
          build_dir: dist  # Directory containing the generated SVGs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
